repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        exclude: (^skyagent/.*)$

  # Black needs to be ran after ruff with --fix
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: (^skyagent/.*)$